name: Ubuntu

on:
  push:
    branches: [ "next", "master", "ci", "sdl2" ]
  pull_request:
    branches: [ "next", "master", "sdl2" ]

env:
  CC: gcc

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - runner: ubuntu-latest
            name: x86_64
          - runner: ubuntu-24.04-arm
            name: aarch64

    name: ${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
    - uses: actions/checkout@v6.0.1

    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt install -y libsdl-mixer1.2-dev libpng-dev

    - name: Build SRB2 Retro
      run: |
        touch src/comptime.h
        make -C src/ --keep-going -j$(nproc) LINUX64=1

    - name: Upload build artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        name: srb2retro-linux-${{ matrix.arch.name }}-${{ github.sha }}
        path: |
          bin/Linux64/Release
          src/comptime.h
